### ISSUE TITLE
Adding device without login_name

### ISSUE THREAD

**Issue by ceaveson** [ceaveson/sshm#1]
PS C:\Users\ceaveson> nslookup fwd001-dcs-clstr
Server:  UnKnown
Address:  10.100.0.4

Name:    fwd001-dcs-clstr.gammatelecom.com
Address:  10.4.0.145

PS C:\Users\ceaveson> sshm add -h fwd001-dcs-clstr -ip 10.4.0.145 -m Fortinet
Traceback (most recent call last):
  File "C:\Users\ceaveson\AppData\Local\Microsoft\WindowsApps\sshm.py", line 434, in <module>
    cli()
  File "C:\Python310\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Python310\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python310\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\ceaveson\AppData\Local\Microsoft\WindowsApps\sshm.py", line 156, in add
    table.add_row(host["hostname"], host["IP"], host["manufacturer"], host["login_name"])
KeyError: 'login_name'
PS C:\Users\ceaveson> sshm show -h fwd001
                                     hosts
┌─────┬──────────────────┬──────────────┬──────────────┬──────────────┬────────┐
│ Key │ Hostname         │           IP │ Manufacturer │   Login Name │ Source │
├─────┼──────────────────┼──────────────┼──────────────┼──────────────┼────────┤
│ 341 │ FWD001-LAN-EXP   │  94.75.74.99 │     Fortinet │              │  local │
│ 342 │ fwd001-bud-clstr │ 10.12.20.245 │     Fortinet │ netops-admin │  local │
│ 343 │ fwd001-dcs-clstr │   10.4.0.145 │     Fortinet │              │  local │
│ 344 │ fwd001-dcs-hex   │    10.4.2.19 │     Fortinet │              │ netbox │
│ 345 │ fwd001-dcs-tra   │    10.4.0.19 │     Fortinet │              │ netbox │
└─────┴──────────────────┴──────────────┴──────────────┴──────────────┴────────┘
PS C:\Users\ceaveson>

**Comment by ceaveson** [comment]
Fixed and added test to catch an issue like this in the future.
